module.exports = {
  important: true,
  // mode: 'jit',
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    boxShadow: {
      md: '0px 4px 8px rgba(0, 0, 0, 0.05), 0px 2px 4px rgba(0, 0, 0, 0.07), 0px 1px 2px rgba(0, 0, 0, 0.1)',
      mdHover: '0px 2px 4px rgba(0, 0, 0, 0.1), 0px 6px 12px rgba(0, 0, 0, 0.07), 0px 12px 24px rgba(0, 0, 0, 0.05)',
    },
    opacity: {
      '0': '0',
      '25': '.25',
      '75': '.75',
      '10': '.1',
      '20': '.2',
      '30': '.3',
      '40': '.4',
      '50': '.5',
      '60': '.6',
      '70': '.7',
      '80': '.8',
      '90': '.9',
      '100': '1'
    },
    maxHeight: {
      '0': '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      'full': '100%',
      '7r': '7rem',
      '20r': '20rem',
      '40r': '40rem',
      '50r': '50rem',
      'screen': '100vh'
    },
    aspectRatio: { // defaults to {}
      'square': [1, 1],
      '16/9': [16, 9],
      '4/3': [4, 3]
    },
    extend: {
      opacity: {
        '06': '.06',
      },
      minHeight: {
        'tag-selector-input': '66px',
        '48': '12rem'
      },
      minWidth: {
        '0': '0',
        '1/4': '25%',
        '1/2': '50%',
        '60p': '60%',
        '3/4': '75%',
        '9/10': '90%',
        'full': '100%',
        'over': '260%',
        'program-card': '300px',
        'alumni-card': '480px',
        'reward-card': '320px',
        'top-3-card': '320px'
      },
      maxWidth: {
        '10p': '10%',
        '20p': '20%',
        '30p': '30%',
        '40p': '40%',
        '50p': '50%',
        '60p': '60%',
        '70p': '70%',
        '80p': '80%',
        '90p': '90%',
        '0': '0',
        '25': '25%',
        '1/4': '25%',
        '12': '12rem',
        '16': '16rem',
        '24': '24rem',
        '26': '26rem',
        '30': '30rem',
        '50rem': '50rem',
        '50': '50%',
        '3/5': '60%',
        '70': '70%',
        '3/4': '75%',
        '75': '75%',
        '90': '90%',
        'full': '100%',
        '104': '26rem',
        'modal-desktop': '1100px',
        'program-card': '300px',
        'alumni-card': '480px',
        'reward-card': '320px',
        'top-3-card': '320px'
      },
      colors: {
        mist: '#5c6ac4',
        lagune: '#007ace',
        lava: '#ff654a',
        'lava-dark': '#D9563F',
        forest: '#023436',
        grass: '#83d6a0',
        sky: '#d2eeee',
        corail: '#ff9180',
        green: '#0A6E77',

        //V2 // IMPORTANT: THEY HAVE TO BE SYNCED TO COLORS in _colors.scss
        'blue-lagune': 'var(--color-blue-lagune)',
        'blue-lagune-washed-out': 'var(--color-blue-lagune-washed-out)',
        'blue-lagune-darken': 'var(--color-blue-lagune-darken)',
        'gradient-blue-lagune': 'var(--gradient-blue-lagune)',

        'green-grass': 'rgb(131,214,160)',
        'green-grass-washed-out': 'var(--color-green-grass-washed-out)',
        'green-grass-darken': 'var(--color-green-grass-darken: #76C190)',

        'blue-washed': 'rgb(230, 238, 238)',
        'blue-sky': 'rgb(210, 238, 238)',
        'blue-sky-washed-out': 'var(--color-blue-sky-washed-out)',
        'blue-sky-darken': 'var(--color-blue-sky-darken)',

        'orange-lava': 'var(--color-orange-lava)',
        'orange-lava-washed-out': 'var(--color-orange-lava-washed-out)',
        'orange-lava-darken': 'var(--color-orange-lava-darken)',

        'pure-white': 'var(--grey-scale-pure-white)',
        'white': 'var(--grey-scale-white)',
        'white-faded': 'rgb(105,166,171)',
        'white-faded-more': 'var(--grey-scale-white-faded-more)',
        'light-gray': 'var(--grey-scale-light-gray)',
        'gray': 'rgb(216,222,222)',
        'dark-gray': 'var(--grey-scale-dark-gray)',
        'black-forest': 'rgb(2,52,54)',
        'black-forest-faded': 'var(--grey-scale-black-forest-faded)',
      },
      fontSize: {
        'xxs': '0.625rem',
        '2': '2rem',
        'label': ['12px', { lineHeight: '12px', letterSpacing: '1px' }],
        'link': ['14px', { lineHeight: '14px' }],
        'body': ['16px', { lineHeight: '24px' }],
        'headline-5': ['16px', { letterSpacing: '-1%', lineHeight: '20px' }],
        'headline-4': ['20px', { letterSpacing: '-1%', lineHeight: '24px' }],
        'headline-3': ['24px', { letterSpacing: '-2%' }],
        // 'headline-3': ['24px', { letterSpacing: '-2%', lineHeight: '28px' }],
        'headline-2': ['32px', { letterSpacing: '-3%', lineHeight: '40px' }],
        'headline-1-5': ['48px', { letterSpacing: '-4%', lineHeight: '48px' }],
        'headline-1': ['56px', { letterSpacing: '-4%', lineHeight: '56px' }],
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
      },
      padding: {
        '1.5': '0.375rem',
        '7': '1.75rem',
        'btn-round': '8px',
        'btn-small': '9px 16px',
        'btn-medium': '13px 24px',
        'btn-large': '17px 32px',
        'btn-extra-large': '25px 40px',
        'tag-medium': '8px 12px',
        'card-button-medium': '26px 40px',
        'card-button-small': '15px 20px 30px',
        'card-medium': '24px',
        '18': '4.5rem',
        'page-mobile': '1.25rem',
        'tag-selector': '0.50rem'
      },
      margin: {
        '1.5': '0.375rem',
        '7': '1.75rem',
        'card-medium': '24px 24px 24px 32px',
        'page-mobile': '1.25rem'
      },
      height: {
        '18': '4.5rem',
        'header': '56px',
        'icon-small': '0.7rem',
        'icon-medium': '14px',
        'icon-large': '1.3rem',
        'avatar-small': '32px',
        'avatar-medium': '56px',
        'avatar-large': '120px',
        'avatar-extra-large': '144px',
        'pie-chart-small': '104px',
        'pie-chart-medium': '128px',
      },
      width: {
        '14': '14rem',
        '18': '4.5rem',
        '68': '17rem',
        '104': '26rem',
        '164': '41rem',
        'icon-small': '0.7rem',
        'icon-medium': '14px',
        'icon-large': '1.3rem',
        'avatar-small': '32px',
        'avatar-medium': '56px',
        'avatar-large': '120px',
        'avatar-extra-large': '144px',
        'modal-desktop': '120px',
        'pie-chart-small': '104px',
        'pie-chart-medium': '128px',
      },
      inset: {
        'close-icon-pos': '15px',
        'header': '56px'
      },
      borderRadius: {
        tiny: '8px',
        small: '12px',
        medium: '16px',
        'medium-more': '24px',
        large: '32px',
      },
      rotate: {
        '15': '15deg',
        'neg-15': '-15deg',
      },
      zIndex: {
        '1': '1',
        '2': '2'
      },
    }
  },
  // separator: '_',
  variants: {
    aspectRatio: ['responsive'], // defaults to ['responsive']
  },
  // plugins: [
  //   require('tailwindcss-aspect-ratio'),
  // ],
  purge: [
    './src/**/*.html',
    './src/**/*.vue',
  ],
}
